[project]
name = "streaming-project"
version = "0.1.0"
description = "This is a real time streaming pipeline"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "faker>=38.2.0",
    "fastapi[standard]>=0.121.3",
    "kafka-python>=2.3.0",
]
